FROM node:16-alpine AS development 

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to work directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
# RUN npm run build

# Use NGINX as a lightweight web server to serve the static files
# FROM nginx:alpine

# Copy the build files from the previous stage to NGINX's web root directory
# COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 8080

# Start NGINX when the container starts
CMD ["npm", "start"]